package samba

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"net"
	"path/filepath"
	"sort"
	"strings"

	"github.com/netos-router/netos/internal/config"
	"github.com/netos-router/netos/internal/subsys/vpnservers"
)

func token(id string) string                  { h := sha256.Sum256([]byte(id)); return hex.EncodeToString(h[:10]) }
func MountPath(v config.StorageVolume) string { return "/srv/netos/" + token(v.ID) }
func mountUnit(v config.StorageVolume) string { return "srv-netos-" + token(v.ID) + ".mount" }
func account(id string) string                { return "nosmb" + token(id) }
func selected(ids []string, id string) bool {
	for _, v := range ids {
		if v == id {
			return true
		}
	}
	return false
}

// Access separates interface selection from source ranges, including PPP and
// policy-based IPsec where the transport's public interface is not the client.
type Access struct {
	Interface, Subnet string
	IPsec             bool
}

func Accesses(c *config.Config) []Access {
	var out []Access
	for _, n := range c.Networks {
		if n.Enabled && selected(c.Samba.Networks, n.ID) {
			_, sub, e := net.ParseCIDR(n.RouterAddress)
			if e == nil {
				out = append(out, Access{Interface: c.InterfaceName(n.Interface), Subnet: sub.String()})
			}
		}
	}
	for _, v := range c.VPNServers {
		if v.Enabled && v.Type != "xray" && selected(c.Samba.VPNs, v.ID) {
			_, sub, e := net.ParseCIDR(v.Subnet)
			if e == nil {
				out = append(out, Access{Interface: vpnservers.MatchInterfaceName(v), Subnet: sub.String(), IPsec: v.Type == "ikev2"})
			}
		}
	}
	return out
}

func Render(c *config.Config, dir string) (string, error) {
	var b strings.Builder
	workgroup := c.Samba.Workgroup
	if workgroup == "" {
		workgroup = "WORKGROUP"
	}
	interfaces := []string{"lo"}
	hosts := []string{"127.0.0.1"}
	for _, a := range Accesses(c) {
		interfaces = append(interfaces, `"`+strings.ReplaceAll(a.Interface, "+", "*")+`;options=dynamic"`)
		hosts = append(hosts, a.Subnet)
	}
	sort.Strings(interfaces)
	sort.Strings(hosts)
	fmt.Fprintf(&b, "# Generated by netOS\n[global]\n  server role = standalone server\n  workgroup = %s\n  server string = netOS file server\n  security = user\n  map to guest = Never\n  server min protocol = SMB2_02\n  smb ports = 445\n  disable netbios = yes\n  interfaces = %s\n  bind interfaces only = yes\n  hosts allow = %s\n  hosts deny = ALL\n  load printers = no\n  disable spoolss = yes\n  printing = bsd\n  printcap name = /dev/null\n  usershare max shares = 0\n  unix extensions = no\n  wide links = no\n  follow symlinks = no\n  passdb backend = smbpasswd:%s\n  username map = %s\n  private dir = %s\n  state directory = %s\n  cache directory = %s\n  lock directory = %s\n  pid directory = %s\n  logging = systemd\n", workgroup, strings.Join(interfaces, " "), strings.Join(hosts, " "), filepath.Join(dir, "samba", "smbpasswd"), filepath.Join(dir, "samba", "users.map"), filepath.Join(dir, "samba"), filepath.Join(dir, "samba"), filepath.Join(dir, "samba"), filepath.Join(dir, "samba"), filepath.Join(dir, "samba"))
	for _, sh := range c.Samba.Shares {
		if !sh.Enabled {
			continue
		}
		var volume config.StorageVolume
		for _, v := range c.Samba.Volumes {
			if v.ID == sh.Volume && v.Enabled {
				volume = v
			}
		}
		if volume.ID == "" {
			return "", fmt.Errorf("share %s: volume unavailable", sh.Name)
		}
		var users []string
		for _, id := range sh.Users {
			users = append(users, account(id))
		}
		readOnly := "yes"
		if !sh.ReadOnly {
			readOnly = "no"
		}
		fmt.Fprintf(&b, "\n[%s]\n  path = %s\n  browseable = yes\n  guest ok = no\n  read only = %s\n  valid users = %s\n  force user = netos-storage\n  create mask = 0660\n  directory mask = 0770\n  root preexec = %s %s %s\n  root preexec close = yes\n", sh.Name, MountPath(volume), readOnly, strings.Join(users, " "), filepath.Join(dir, "samba", "check-volume"), MountPath(volume), volume.UUID)
	}
	return b.String(), nil
}

// Accessing /. first triggers the automount; mountpoint alone would accept
// the autofs placeholder. Verify the filesystem UUID before exposing data.
const mountGuard = `#!/bin/sh
set -eu
test "$#" = 2
case "$1" in /srv/netos/*) ;; *) exit 1;; esac
/usr/bin/stat "$1/." >/dev/null
test "$(/usr/bin/findmnt -rn -T "$1/." -t noautofs -o FSTYPE)" != autofs
test "$(/usr/bin/findmnt -rn -T "$1/." -t noautofs -o UUID | /usr/bin/tr '[:upper:]' '[:lower:]')" = "$(printf '%s' "$2" | /usr/bin/tr '[:upper:]' '[:lower:]')"
/usr/bin/mountpoint -q "$1"
`

func mountText(v config.StorageVolume, uid, gid string) string {
	fs := v.Filesystem
	options := "nodev,nosuid,noexec"
	if fs == "ntfs" {
		fs = "ntfs-3g"
	}
	if v.Filesystem == "ntfs" || v.Filesystem == "vfat" || v.Filesystem == "exfat" {
		options += ",uid=" + uid + ",gid=" + gid + ",fmask=0117,dmask=0007"
	}
	return fmt.Sprintf("[Unit]\nDescription=netOS USB volume\nJobTimeoutSec=10s\n[Mount]\nWhat=/dev/disk/by-uuid/%s\nWhere=%s\nType=%s\nOptions=%s\nTimeoutSec=10s\n", v.UUID, MountPath(v), fs, options)
}
func automountText(v config.StorageVolume) string {
	return fmt.Sprintf("[Unit]\nDescription=netOS USB automount\n[Automount]\nWhere=%s\nDirectoryMode=0755\nTimeoutIdleSec=60\n[Install]\nWantedBy=multi-user.target\n", MountPath(v))
}
func sambaUnit(dir string) string {
	return "[Unit]\nDescription=netOS Samba\nAfter=network.target\n[Service]\nType=simple\nExecStart=/usr/sbin/smbd --foreground --no-process-group --configfile=" + filepath.Join(dir, "samba.conf") + "\nExecReload=/bin/kill -HUP $MAINPID\nRestart=on-failure\nUMask=0077\n[Install]\nWantedBy=multi-user.target\n"
}
func discoveryUnit(c *config.Config) string {
	workgroup := c.Samba.Workgroup
	if workgroup == "" {
		workgroup = "WORKGROUP"
	}
	args := ""
	for _, n := range c.Networks {
		if n.Enabled && selected(c.Samba.Networks, n.ID) {
			args += " -i " + c.InterfaceName(n.Interface)
		}
	}
	return "[Unit]\nDescription=netOS Windows network discovery\nAfter=network.target netos-samba.service\n[Service]\nType=simple\nUser=netos-storage\nNoNewPrivileges=yes\nProtectSystem=strict\nProtectHome=yes\nPrivateTmp=yes\nExecStart=/usr/bin/wsdd --ipv4only --hostname " + c.System.Hostname + " --workgroup " + workgroup + args + "\nRestart=on-failure\n[Install]\nWantedBy=multi-user.target\n"
}
