#!/bin/bash
set -euo pipefail

if [[ $# -ne 3 || "$1" != /var/backups/netos/qa-* || "$2" != /var/backups/netos/qa-* || "$3" != /var/backups/netos/netos-*.tar.gz ]]; then
    echo "usage: qa-compare-state.sh BEFORE AFTER BACKUP" >&2
    exit 2
fi

before=$1
after=$2
backup=$3
for path in "$before" "$after" "$backup"; do
    [[ -e "$path" ]] || { echo "missing: $path" >&2; exit 1; }
done

failures=0

verify_manifest() {
    snapshot=$1
    if (cd "$snapshot" && sha256sum -c manifest.sha256 >/dev/null); then
        echo "PASS manifest ${snapshot##*/}"
    else
        echo "FAIL manifest ${snapshot##*/}"
        failures=$((failures + 1))
    fi
}

compare_exact() {
    name=$1
    if [[ ! -e "$before/$name" || ! -e "$after/$name" ]]; then
        echo "FAIL missing snapshot field $name"
        failures=$((failures + 1))
    elif cmp -s "$before/$name" "$after/$name"; then
        echo "IDENTICAL $name"
    else
        echo "CHANGED $name"
        { diff -u "$before/$name" "$after/$name" || true; } | sed -n '1,80p'
        failures=$((failures + 1))
    fi
}

compare_iptables() {
    name=$1
    if [[ ! -e "$before/$name" || ! -e "$after/$name" ]]; then
        echo "FAIL missing snapshot field $name"
        failures=$((failures + 1))
        return
    fi
    left=$(mktemp)
    right=$(mktemp)
    sed -E '/^# (Generated by|Completed on) /d; s/^(:[^ ]+ [^ ]+) \[[0-9]+:[0-9]+\]$/\1 [0:0]/' "$before/$name" > "$left"
    sed -E '/^# (Generated by|Completed on) /d; s/^(:[^ ]+ [^ ]+) \[[0-9]+:[0-9]+\]$/\1 [0:0]/' "$after/$name" > "$right"
    if cmp -s "$left" "$right"; then
        echo "IDENTICAL $name (dynamic counters/timestamps ignored)"
    else
        echo "CHANGED $name"
        { diff -u "$left" "$right" || true; } | sed -n '1,80p'
        failures=$((failures + 1))
    fi
    rm -f -- "$left" "$right"
}

verify_manifest "$before"
verify_manifest "$after"

echo "EXACT_HOST_STATE"
for name in \
    os-release.txt uname.txt packages.tsv packages-manual.txt \
    host-service-state.txt netos-unit-health.txt \
    ip-link-brief.txt ip-address-brief.txt ip-rule-v4.txt ip-rule-v6.txt \
    ip-route-v4.txt ip-route-v6.txt \
    ipset-save.txt bridge-link.txt listeners-stable.txt tc-config.txt \
    resolv-stat.txt resolv-content.txt hostname.txt timezone.txt \
    sysctl-managed.txt sysctl-per-interface.txt managed-system-files.txt
do
    compare_exact "$name"
done
compare_iptables iptables-save.txt
compare_iptables ip6tables-save.txt

echo "RENDERED_ARTIFACTS"
for old in "$before"/render-*.txt; do
    name=${old#"$before"/}
    [[ "$name" == "render-sha256.txt" ]] && continue
    if [[ ! -e "$after/$name" ]]; then
        echo "MISSING $name"
        failures=$((failures + 1))
    elif cmp -s "$old" "$after/$name"; then
        echo "IDENTICAL $name"
    else
        echo "CHANGED $name"
        failures=$((failures + 1))
    fi
done

echo "PACKAGE_DELTA"
comm -23 "$before/packages.tsv" "$after/packages.tsv" | sed 's/^/REMOVED /'
comm -13 "$before/packages.tsv" "$after/packages.tsv" | sed 's/^/ADDED /'

tmp=$(mktemp -d)
case "$tmp" in /tmp/*) ;; *) echo "unsafe temp path: $tmp" >&2; exit 1 ;; esac
trap 'rm -rf -- "$tmp"' EXIT
tar -C "$tmp" -xzf "$backup"

echo "BACKUP_VS_LIVE"
for path in etc/netos/tls var/lib/netos/generated; do
    if diff -qr "$tmp/$path" "/$path" >/dev/null; then
        echo "IDENTICAL $path"
    else
        echo "CHANGED $path"
        { diff -qr "$tmp/$path" "/$path" || true; } | sed -n '1,20p'
        failures=$((failures + 1))
    fi
done

echo "RUNTIME_SUMMARY"
grep -E '^(NRestarts|SubState|ActiveState)=' < <(systemctl show netosd -p NRestarts -p SubState -p ActiveState)
plan=$(netos plan)
printf '%s\n' "$plan" | sed -n '1,3p'
if ! grep -Fq 'Живая система соответствует конфигурации: применять нечего.' <<< "$plan"; then
    echo "FAIL netos plan is not clean"
    failures=$((failures + 1))
fi
if [[ ! -s /run/netosd.ready ]]; then
    echo "FAIL /run/netosd.ready is missing or empty"
    failures=$((failures + 1))
fi
failed_units=$(systemctl --failed --no-legend --plain)
if [[ -n "$failed_units" ]]; then
    echo "FAIL failed systemd units"
    printf '%s\n' "$failed_units" | sed -n '1,20p'
    failures=$((failures + 1))
else
    echo "PASS no failed systemd units"
fi

if [[ "$failures" -ne 0 ]]; then
    echo "FAIL: $failures state comparison checks"
    exit 1
fi
echo "PASS: exact before/after host state and restored artifacts"
